package: definitions
version: 1.2.0
author: Joachim Doerr
supportpage: https://github.com/basecondition/definitions

requires:
  redaxo: "^5.15"
  php:
    version: "^8.1"

# Neue Konfigurationsoptionen
config:
  base_path: "definitions"
  definition_keys:
    navigation: "navigation/*.yml"
    template: "template/*.yml"
    module: "module/*/*.yml"

## Backend Seiten
#page:
#  title: 'translate:title'
#  perm: admin
#  icon: rex-icon fa-code
#  subpages:
#    settings:
#      title: 'translate:settings'
#      icon: rex-icon fa-cog
#      perm: admin[]
#    readme:
#      title: 'translate:documentation'
#      icon: rex-icon fa-book
#      perm: admin[]
#      itemclass: pull-right
